version: "3.7"
services:

  portainer:
    image: portainer/portainer-ce:latest
#    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
    #  - "9000:9000"
    #  - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - nginx
    restart: unless-stopped


#TODO set up postgres / other db
#TODO set up eclipse-mosquito so that it is also here like homeassistant
networks:
  nginx:
    name: nginx_network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd12:3456:789a:1::/64

volumes:
  portainer_data:
    external: true