version: '3.7'
services:
  home-assistant:
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /portainer/Files/AppData/Config/homeassistant:/config
    network_mode: host
    image: 'ghcr.io/home-assistant/home-assistant:stable'