version: "3.7"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
      #ports:
      #- "8096:8096/tcp"
    #- "8920:8920/udp"
    environment:
      - TZ=Europe/Berlin
      - HOME=/root
      - PGID=1000
      - PUID=1000
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_STAGE2_HOOK=/docker-mods
      - S6_VERBOSITY=1
      - VIRTUAL_ENV=/lsiopy
      - TERM=xterm
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin:/config
      - /sync/asmr:/data/asmr
      - /sync/Movies:/data/movies
      - /sync/music:/data/music
      - /sync/TV:/data/tvshows
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx_internal