version: "2.1"
services:
  speedtest-tracker:
    image: henrywhitaker3/speedtest-tracker:dev-arm
    container_name: speedtest-tracker
    hostname: speedtest-tracker #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - OOKLA_EULA_GDPR=true
    volumes:
      - /portainer/Files/AppData/Config/speedtest-tracker:/config
#    ports:
#      - 7203:443/tcp
#      - 7202:80/tcp
networks:
  default:
    name: nginx_network
    external: true