version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /portainer/Files/AppData/Config:/config
      - /sync:/var/syncthing
#    ports:
#      - 22000:22000/tcp
#      - 22000:22000/udp
#      - 21027:21027/udp
networks:
  default:
    name: nginx_network
    external: true