version: "3.7"
services:
  services:
  server:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - forgejo
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '222:22'
networks:
  nginx:
    name: nginx_network
    enable_ipv6: true
    external: true
    ipam:
      config:
        - subnet: fd12:3456:789a:1::/64
