version: "3.7"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - S6_STAGE2_HOOK=/docker-mods
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - TERM=xterm
    volumes:
      - /sync/calibre:/book
      - /portainer/Files/AppData/Config/calibreweb:/config
    restart: unless-stopped
    networks:
      - nginx_network
networks:
  nginx_network:
    name: nginx_network
    external: true