version: "3.7"
services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - PUID=1000
      - PGID=1000
      - USERID=1000
      - GROUPID=1000
      - PERMISSIONS=true
      - TZ:Europe/Berlin
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    volumes:
      - /sync:/share
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    networks:
      - default
    command: '-s "sync;/share;yes;no;yes;svollmer" -u "svollmer;rT7VNUvMQ9Z4oAazrzLo" -p'
networks:
  default:
