version: "3.7"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    depends_on:
      - nginx-proxy-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - S6_STAGE2_HOOK=/docker-mods
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
      - TERM=xterm
    volumes:
      - /sync/calibre:/book
      - /portainer/Files/AppData/Config/calibreweb:/config
    restart: unless-stopped
    networks:
      - nginx
    ports:
      - "8083:8083"


  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall #optional
    depends_on:
      - nginx-proxy-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /portainer/Files/AppData/Config/Heimdall:/config
    restart: unless-stopped
    networks:
      - nginx

  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
    depends_on:
      - nginx-proxy-manager
    networks:
      - nginx
    #ports:
    #- "8096:8096/tcp"
    #- "8920:8920/udp"
    environment:
      - TZ=Europe/Berlin
      - HOME=/root
      - PGID=1000
      - PUID=1000
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_STAGE2_HOOK=/docker-mods
      - S6_VERBOSITY=1
      - VIRTUAL_ENV=/lsiopy
      - TERM=xterm
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin:/config
      - /sync/asmr:/data/asmr
      - /sync/Movies:/data/movies
      - /sync/music:/data/music
      - /sync/TV:/data/tvshows
      - /sync/youtube:/data/youtube
      - /sync/music_video:/data/music_video
      - /sync:/sync
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

networks:
  nginx:
    name: nginx_network
    enable_ipv6: true
    external: true
    ipam:
      config:
        - subnet: fd12:3456:789a:1::/64
