version: "3.7"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /sync/calibre:/book
      - /portainer/Files/AppData/Config/calibreweb:/config
    restart: unless-stopped
    networks:
      - nginx
    ports:
      - "8083:8083"

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    hostname: heimdall #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /portainer/Files/AppData/Config/Heimdall:/config
    restart: unless-stopped
    networks:
      - nginx

  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: linuxserver/jellyfin:latest
    networks:
      - nginx
    #ports:
    #- "8096:8096/tcp"
    #- "8920:8920/udp"
    environment:
      - TZ=Europe/Berlin
      - HOME=/root
      - PGID=1000
      - PUID=1000
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_STAGE2_HOOK=/docker-mods
      - S6_VERBOSITY=1
      - VIRTUAL_ENV=/lsiopy
      - TERM=xterm
    volumes:
      - /portainer/Files/AppData/Config/Jellyfin:/config
      - /sync/asmr:/data/asmr
      - /sync/Movies:/data/movies
      - /sync/music:/data/music
      - /sync/TV:/data/tvshows
      - /sync/youtube:/data/youtube
      - /sync/music_video:/data/music_video
      - /sync:/sync
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  navidrome:
      image: deluan/navidrome:latest
      user: 1000:1000 # should be owner of volumes
      restart: unless-stopped
      environment:
        # Optional: put your config options customization here. Examples:
        ND_SCANSCHEDULE: 1h
        ND_LOGLEVEL: info
        ND_SESSIONTIMEOUT: 24h
        ND_BASEURL: ""
        ND_PORT: 4533
      volumes:
        - "/portainer/Files/AppData/Config/navidrome:/data"
        - "/sync/music:/music:ro"
networks:
  nginx:
    name: nginx_network
    external: true