version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud

  app:
    container_name: nextcloud
    image: nextcloud:apache
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/nextcloud:/var/www/html
      - /sync:/sync
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - REDIS_HOST=redis
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=1G
    depends_on:
      - redis
    networks:
      - db_net
      - nginx
      - nextcloud

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - redis

networks:
  nginx:
    name: nginx_network
    external: true
  nextcloud:
  db_net:
    name: db_net
    external: true
