version: '3.3'

services:
  firefly:
    container_name: firefly
    image: fireflyiii/core:latest
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: 
      - ../stack.env
    depends_on:
      - db
    networks:
      - back-tier
      - nginx
  db:
    image: mariadb
    container_name: fireflydb
    hostname: fireflydb
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=%{DB_PASSWORD}
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - back-tier
  
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly:8080/api/v1/cron/${STATIC_CRON_TOKEN}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - back-tier
volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  nginx:
    name: nginx-network
    external: true
  back-tier:
  
